[project]
name = "imggen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ben Lambert", email = "blambert@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-auth>=2.45.0",
    "google-cloud-storage>=3.7.0",
    "numpy>=2.2.1",
    "opencv-python>=4.10.0",
    "pillow>=12.0.0",
    "pydantic>=2.12.5",
    "typer>=0.21.0",
]

[project.optional-dependencies]
ml = [
    "accelerate>=1.12.0",
    "diffusers>=0.36.0",
    "ftfy>=6.3.1",
    "peft>=0.18.0",
    "protobuf>=6.33.2",
    "pyyaml>=6.0.2",
    "qwen-vl-utils>=0.0.14",
    "sentencepiece>=0.2.1",
    "torchvision>=0.24.1",
    "transformers>=4.57.3",
    "tqdm>=4.67.1",
    "wandb>=0.19.1",
]
dev = [
    "pytest>=8.3.4",
]

[project.scripts]
vlm-process = "imggen.cmd.vlm_process:app"
detect-logo = "imggen.cmd.detect_logo:app"
caption-images = "imggen.cmd.caption_images:app"
remove-logo = "imggen.cmd.remove_logo:app"
view-vlm-output = "imggen.cmd.view_vlm_output:app"
train-unconditional = "imggen.cmd.train_unconditional:app"
train-lora-sdxl = "imggen.cmd.train_lora_sdxl:app"
train-lora-flux1 = "imggen.cmd.train_lora_flux1:app"
batch-gen = "imggen.cmd.batch_gen:app"
gen-flux1 = "imggen.cmd.gen_flux1:app"
gen-qwenimage = "imggen.cmd.gen_qwenimage:app"
print-flux-model = "imggen.cmd.print_flux_model:app"
print-t5-model = "imggen.cmd.print_t5_model:app"

[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"

[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
